{% set name = "mlx-lm" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 4485c05067a2fcf6746c2c918df460d0770b3411454730351d000ca1bd38b36f
  # As there is no tag in the mlx-examples repo, we need to reference a commit here.
  - url: https://raw.githubusercontent.com/ml-explore/mlx-examples/a932012c1291b675e74f899d671883b7c41eb0db/LICENSE
    fn: LICENSE
    sha256: ccfab7ccb2ea306f71531c8ca77bb55507606cd90768b1e32b8b52ab5b48cf01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - sentencepiece
    - jinja2
    - pyyaml
    - python >={{ python_min }}
    - mlx >=0.29.2
    - numpy
    - transformers ==5.0.0rc1
    - protobuf

test:
  imports:
    - mlx_lm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ml-explore/mlx-examples
  summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mlx
    - sugatoray
