{% set name = "mlx-lm" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 5df8aa87504df28bd77c91be09f68c551bde6f141f204d3b37157f3c3ede26c1
  # As there is no tag in the mlx-examples repo, we need to reference a commit here.
  - url: https://raw.githubusercontent.com/ml-explore/mlx-examples/a932012c1291b675e74f899d671883b7c41eb0db/LICENSE
    fn: LICENSE
    sha256: ccfab7ccb2ea306f71531c8ca77bb55507606cd90768b1e32b8b52ab5b48cf01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - jinja2
    - pyyaml
    - python >={{ python_min }}
    - mlx >=0.25.0
    - numpy
    - transformers >=4.39.3
    - protobuf

test:
  imports:
    - mlx_lm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ml-explore/mlx-examples
  summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mlx
    - sugatoray
