{% set name = "mlx-lm" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlx-lm-{{ version }}.tar.gz
    sha256: 338985ed7ad19fbf672a5fa983560b58a056b5dd3b47f3de587950d428f5304b
  # As there is no tag in the mlx-examples repo, we need to reference a commit here.
  - url: https://raw.githubusercontent.com/ml-explore/mlx-examples/a932012c1291b675e74f899d671883b7c41eb0db/LICENSE
    fn: LICENSE
    sha256: ccfab7ccb2ea306f71531c8ca77bb55507606cd90768b1e32b8b52ab5b48cf01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - mlx
    - numpy
    - transformers
    - protobuf

test:
  imports:
    - mlx_lm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ml-explore/mlx-examples
  summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mlx
    - sugatoray
