{% set name = "mlx-lm" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 07186e71e08180211dc4fd2a86d64564601df900b94b03c33f5a21ede9190b92
  # As there is no tag in the mlx-examples repo, we need to reference a commit here.
  - url: https://raw.githubusercontent.com/ml-explore/mlx-examples/a932012c1291b675e74f899d671883b7c41eb0db/LICENSE
    fn: LICENSE
    sha256: ccfab7ccb2ea306f71531c8ca77bb55507606cd90768b1e32b8b52ab5b48cf01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - jinja2
    - pyyaml
    - python >=3.8
    - mlx >=0.11
    - numpy
    - transformers >=4.39.3
    - protobuf

test:
  imports:
    - mlx_lm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ml-explore/mlx-examples
  summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mlx
    - sugatoray
